# Generated by Django 5.0.6 on 2024-07-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_alter_seo_meta_title'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
