# Generated by Django 5.0.6 on 2024-08-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_logo_alter_store_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
