# Generated by Django 5.0.6 on 2024-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_custom_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='subDomain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
