# Generated by Django 5.0.6 on 2024-08-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_has_custom_domain_store_subdomain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='subDomain',
            new_name='sub_domain',
        ),
    ]
