# Generated by Django 5.0.6 on 2024-08-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_delete_stateshippingcost'),
        ('store', '0005_rename_subdomain_store_sub_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_to_home', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_costs', to='others.state')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_costs', to='store.store')),
            ],
        ),
    ]
