# Generated by Django 5.0.6 on 2024-08-09 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_stateshippingcost_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='seo',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('icon', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='store.store')),
            ],
        ),
    ]
