# Generated by Django 5.0.6 on 2024-08-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_store_seo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
