# Generated by Django 5.0.6 on 2024-08-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_delete_stateshippingcost'),
        ('store', '0009_status_order_alter_status_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateshippingcost',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stateshippingcost',
            name='cost_to_home',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stateshippingcost',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_shipping_costs', to='others.state'),
        ),
    ]
