# Generated by Django 5.0.6 on 2024-08-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_product_quantity'),
        ('store', '0010_alter_stateshippingcost_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker', models.CharField(max_length=40)),
                ('blocked', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(to='orders.order')),
            ],
        ),
    ]
