# Generated by Django 5.0.6 on 2024-08-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
