# Generated by Django 5.0.6 on 2024-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
