# Generated by Django 5.0.6 on 2024-08-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_visitor_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='store.store'),
        ),
    ]
