# Generated by Django 5.0.6 on 2024-08-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_product_quantity'),
        ('store', '0015_alter_visitor_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='orders',
            field=models.ManyToManyField(related_name='visitors', to='orders.order'),
        ),
    ]
