# Generated by Django 5.0.6 on 2024-08-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_visitor_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='orders',
        ),
    ]
