# Generated by Django 5.0.6 on 2024-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_visitor_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='tracker',
            field=models.TextField(blank=True, null=True),
        ),
    ]
