# Generated by Django 5.0.6 on 2024-08-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_blockedipadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedipadress',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ip_addesses', to='store.store'),
        ),
    ]
