# Generated by Django 5.0.6 on 2024-08-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_ipaddress_delete_blockedipadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='store.visitor'),
        ),
    ]
