# Generated by Django 5.0.6 on 2024-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_ipaddress_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateshippingcost',
            name='cost_to_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
