# Generated by Django 5.0.6 on 2024-08-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_gsinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GSInfo',
        ),
    ]
