# Generated by Django 5.0.6 on 2024-08-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_gsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_store', to='store.store')),
            ],
        ),
    ]
