# Generated by Django 5.0.6 on 2024-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_vipstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ask_for_client_note',
            field=models.BooleanField(default=False),
        ),
    ]
