# Generated by Django 5.0.6 on 2024-08-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_store_ask_for_client_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
    ]
