# Generated by Django 5.0.6 on 2024-08-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='borders_rounded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='color_primary',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
