# Generated by Django 5.0.6 on 2024-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_store_borders_rounded_store_color_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
