# Generated by Django 5.0.6 on 2024-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='color_primary',
            field=models.CharField(default='#5d6c99', max_length=7),
        ),
    ]
