# Generated by Django 5.0.6 on 2024-08-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_store_color_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_id', models.CharField(max_length=20)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fb_pixel', to='store.store')),
            ],
        ),
    ]
