# Generated by Django 5.0.6 on 2024-08-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_fbpixel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='color_primary',
            field=models.CharField(default='#446ec3', max_length=7),
        ),
    ]
