# Generated by Django 5.0.6 on 2024-08-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_store_color_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='sub_domain',
        ),
    ]
