# Generated by Django 5.0.6 on 2024-09-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_store_domain_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpixel',
            name='conversion_api_access_token',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
