# Generated by Django 5.0.6 on 2024-09-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_fbpixel_conversion_api_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_id', models.CharField(max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_pixel', to='store.store')),
            ],
        ),
    ]
