# Generated by Django 5.0.6 on 2024-09-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_tiktokpixel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokpixel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_pixels', to='store.store'),
        ),
    ]
