# Generated by Django 5.0.6 on 2024-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_tiktokpixel_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpixel',
            name='test_event_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
