# Generated by Django 5.0.6 on 2024-09-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_fbpixel_test_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpixel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_pixels', to='store.store'),
        ),
    ]
