# Generated by Django 5.0.6 on 2024-09-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_fbpixel_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbpixel',
            name='conversion_api_access_token',
        ),
        migrations.RemoveField(
            model_name='fbpixel',
            name='test_event_code',
        ),
        migrations.CreateModel(
            name='ConversionsApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, max_length=400, null=True)),
                ('test_event_code', models.CharField(blank=True, max_length=20, null=True)),
                ('fb_pixel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_api', to='store.fbpixel')),
            ],
        ),
    ]
