# Generated by Django 5.0.6 on 2024-09-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_fbpixel_conversions_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionsapi',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversions_apis', to='store.store'),
        ),
    ]
