# Generated by Django 5.0.6 on 2024-09-12 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_conversionsapi_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpixel',
            name='conversions_api',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb_pixel', to='store.conversionsapi'),
        ),
    ]
