# Generated by Django 5.0.6 on 2024-09-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_fbpixel_conversions_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='favicon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
