# Generated by Django 5.0.6 on 2024-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_store_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='header_outlined',
            field=models.BooleanField(default=False),
        ),
    ]
