# Generated by Django 5.0.6 on 2024-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_store_header_outlined'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='language',
            field=models.CharField(default='ar', max_length=2),
        ),
    ]
