# Generated by Django 5.0.6 on 2024-09-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_store_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='color_primary_dark',
            field=models.CharField(default='#446ec3', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='mode',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
