# Generated by Django 5.0.6 on 2024-09-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_store_color_primary_dark_store_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
