# Generated by Django 5.0.6 on 2024-09-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_store_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='footer',
            field=models.TextField(default=''),
        ),
    ]
