# Generated by Django 5.0.6 on 2024-09-19 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_options'),
        ('product', '0043_alter_product_options'),
        ('store', '0053_alter_store_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_latest', models.BooleanField(default=True)),
                ('selected_categories', models.ManyToManyField(to='category.category')),
                ('selected_products', models.ManyToManyField(to='product.product')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_design', to='store.store')),
            ],
        ),
    ]
