# Generated by Django 5.0.6 on 2024-09-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_homepagedesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagedesign',
            name='order',
            field=models.JSONField(default={'catgories-products': 3, 'latest-products': 2, 'selected-products': 1}),
        ),
    ]
