# Generated by Django 5.0.6 on 2024-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_homepagedesign_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedesign',
            name='order',
            field=models.JSONField(default=dict),
        ),
    ]
