# Generated by Django 5.0.6 on 2024-09-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_homepagedesign_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagedesign',
            old_name='order',
            new_name='orders',
        ),
    ]
