# Generated by Django 5.0.6 on 2024-09-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_store_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagedesign',
            name='get_latest',
        ),
    ]
