# Generated by Django 5.0.6 on 2024-09-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_rename_storetoppicks_storetoppick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreTopPick',
        ),
    ]
