# Generated by Django 5.0.6 on 2024-09-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_storetoppick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageDesign',
        ),
    ]
