# Generated by Django 5.0.6 on 2024-10-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_categorypreviewproduct'),
        ('product', '0043_alter_product_options'),
        ('store', '0064_delete_homepagedesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_page', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('design', models.JSONField()),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('products', models.ManyToManyField(to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='store.homepage')),
                ('imageObejcts', models.ManyToManyField(to='store.imageobject')),
            ],
        ),
    ]
