# Generated by Django 5.0.6 on 2024-10-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_imageobject_homepage_homepagesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesection',
            name='active',
        ),
    ]
