# Generated by Django 5.0.6 on 2024-10-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_remove_homepagesection_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesection',
            old_name='store',
            new_name='HomePage',
        ),
    ]
