# Generated by Django 5.0.6 on 2024-10-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_rename_store_homepagesection_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesection',
            name='imageObejcts',
        ),
        migrations.DeleteModel(
            name='ImageObject',
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='imageObejcts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
