# Generated by Django 5.0.6 on 2024-10-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_remove_homepagesection_imageobejcts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesection',
            old_name='imageObejcts',
            new_name='image_obejcts',
        ),
    ]
