# Generated by Django 5.0.6 on 2024-10-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_rename_image_obejcts_homepagesection_image_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='design',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
