# Generated by Django 5.0.6 on 2024-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_alter_homepagesection_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='general_design',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
