# Generated by Django 5.0.6 on 2024-10-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_homepage_general_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesection',
            old_name='HomePage',
            new_name='home_page',
        ),
    ]
