# Generated by Django 5.0.6 on 2024-10-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_rename_homepage_homepagesection_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
