# Generated by Django 5.0.6 on 2024-10-03 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_categorypreviewproduct'),
        ('store', '0074_homepagesection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_section', to='category.category'),
        ),
    ]
