# Generated by Django 5.0.6 on 2024-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_alter_homepagesection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
