# Generated by Django 5.0.6 on 2024-10-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_homepagesection_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
