# Generated by Django 5.0.6 on 2024-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_homepagesection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='credit',
            field=models.BigIntegerField(default=300),
        ),
    ]
