# Generated by Django 5.0.6 on 2024-10-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_store_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
