# Generated by Django 5.0.6 on 2024-10-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_store_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='credit',
        ),
    ]
