# Generated by Django 5.0.6 on 2024-10-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_remove_store_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='plan',
        ),
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.BigIntegerField(default=300)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='StorePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=10, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='store.store')),
            ],
        ),
    ]
