# Generated by Django 5.0.6 on 2024-10-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_remove_store_plan_storecredit_storeplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeplan',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='credit',
            field=models.BigIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='store',
            name='plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='StoreCredit',
        ),
        migrations.DeleteModel(
            name='StorePlan',
        ),
    ]
