# Generated by Django 5.0.6 on 2024-10-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_remove_storeplan_store_store_credit_store_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesection',
            name='device',
        ),
    ]
