# Generated by Django 5.0.6 on 2024-10-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_homepagesection_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesection',
            name='device',
        ),
    ]
