# Generated by Django 5.0.6 on 2024-10-11 21:29

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_remove_homepagesection_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='device',
            field=models.JSONField(blank=True, default=store.models.default_device, null=True),
        ),
    ]
