# Generated by Django 5.0.6 on 2024-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_homepagesection_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='auto',
            field=models.BooleanField(default=True),
        ),
    ]
