# Generated by Django 5.0.6 on 2024-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_homepage_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='show_latest_products',
            field=models.BooleanField(default=True),
        ),
    ]
