# Generated by Django 5.0.6 on 2024-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_homepagesection_show_latest_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='lastest_products_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='show_latest_products',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
