# Generated by Django 5.0.6 on 2024-10-17 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0089_homepagesection_lastest_products_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='lastest_products_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
