# Generated by Django 5.0.6 on 2024-10-18 06:15

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_rename_usedefaultshipping_product_use_default_shipping'),
        ('store', '0090_alter_homepagesection_lastest_products_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(default='default-section', max_length=50)),
                ('type', models.CharField(default='products-container', max_length=50)),
                ('design', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('device', models.JSONField(blank=True, default=store.models.default_device, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_section', to='store.homepage')),
                ('products', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
