# Generated by Django 5.0.6 on 2024-10-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0091_defaultpagesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultpagesection',
            name='order',
        ),
    ]
