# Generated by Django 5.0.6 on 2024-10-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_remove_defaultpagesection_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpagesection',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
