# Generated by Django 5.0.6 on 2024-10-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0093_alter_defaultpagesection_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPageSectionDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.JSONField(blank=True, null=True)),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_section', to='store.homepage')),
            ],
        ),
        migrations.DeleteModel(
            name='DefaultPageSection',
        ),
    ]
