# Generated by Django 5.0.6 on 2024-10-18 06:43

import store.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_alter_defaultpagesectiondesign_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpagesectiondesign',
            name='design',
            field=models.JSONField(blank=True, default=store.constants.default_design, null=True),
        ),
    ]
