# Generated by Django 5.0.6 on 2024-10-18 07:26

import django.db.models.deletion
import store.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_alter_defaultpagesectiondesign_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.JSONField(blank=True, default=store.constants.default_design, null=True)),
                ('title', models.CharField(default='All products', max_length=50)),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_section', to='store.homepage')),
            ],
        ),
        migrations.DeleteModel(
            name='DefaultPageSectionDesign',
        ),
    ]
