# Generated by Django 5.0.6 on 2024-10-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0098_delete_storetoppick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIPStore',
        ),
    ]
