# Generated by Django 5.0.6 on 2024-07-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
