# Generated by Django 5.0.6 on 2024-07-29 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_options'),
        ('others', '0002_alter_seo_meta_title'),
        ('product', '0004_product_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmainimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productmainimage',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productvariantcombination',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariantcombination',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantcombination',
            name='variant_options',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
        migrations.AddField(
            model_name='product',
            name='all_products_related',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prices_and_images_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rich_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selected_categories',
            field=models.ManyToManyField(related_name='products', to='category.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variants_combinations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StateShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='others.state')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductMainImage',
        ),
        migrations.DeleteModel(
            name='ProductVariantCombination',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.DeleteModel(
            name='VariantOption',
        ),
    ]
