# Generated by Django 5.0.6 on 2024-07-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productmainimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
