# Generated by Django 5.0.6 on 2024-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
