# Generated by Django 5.0.6 on 2024-07-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_options'),
        ('product', '0008_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='category.category'),
        ),
    ]
