# Generated by Django 5.0.6 on 2024-07-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_selected_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='all_products_related',
            field=models.BooleanField(default=False),
        ),
    ]
