# Generated by Django 5.0.6 on 2024-07-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_main_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedproduct',
            old_name='related_products',
            new_name='related_product',
        ),
    ]
