# Generated by Django 5.0.6 on 2024-07-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_related_products_relatedproduct_related_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices_and_images_list',
        ),
    ]
