# Generated by Django 5.0.6 on 2024-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_prices_and_images_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prices_and_images_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
