# Generated by Django 5.0.6 on 2024-07-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_prices_and_images_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateshippingcost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states_shipping_cost', to='product.product'),
        ),
    ]
