# Generated by Django 5.0.6 on 2024-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
