# Generated by Django 5.0.6 on 2024-08-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_standard_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='standard_shipping',
        ),
    ]
