# Generated by Django 5.0.6 on 2024-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_original_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateshippingcost',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
