# Generated by Django 5.0.6 on 2024-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_stateshippingcost_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedproduct',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
