# Generated by Django 5.0.6 on 2024-08-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_ask_for_address_product_ask_for_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants_combinations',
        ),
    ]
