# Generated by Django 5.0.6 on 2024-08-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_stateshippingcost_cost_to_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost',
        ),
    ]
