# Generated by Django 5.0.6 on 2024-08-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_stateshippingcost_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
