# Generated by Django 5.0.6 on 2024-08-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_stateshippingcost_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantsCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('combination', models.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_combinations', to='product.product')),
            ],
        ),
    ]
