# Generated by Django 5.0.6 on 2024-08-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_variantscombination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantscombination',
            name='combination',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
