# Generated by Django 5.0.6 on 2024-08-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_variantscombination_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantscombination',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantscombination',
            name='original_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantscombination',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
