# Generated by Django 5.0.6 on 2024-08-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_variantscombination_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices_and_images_list',
        ),
    ]
