# Generated by Django 5.0.6 on 2024-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_has_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
