# Generated by Django 5.0.6 on 2024-08-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_product_max_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ask_for_city',
        ),
    ]
