# Generated by Django 5.0.6 on 2024-09-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_remove_product_ask_for_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
