# Generated by Django 5.0.6 on 2024-10-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='useDefaultShipping',
            field=models.BooleanField(default=True),
        ),
    ]
