# Generated by Django 5.0.6 on 2024-10-22 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_rename_usedefaultshipping_product_use_default_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_test', to='product.product')),
            ],
        ),
    ]
