# Generated by Django 5.0.6 on 2024-10-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_testproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testproduct',
            old_name='Product',
            new_name='prroduct',
        ),
    ]
