# Generated by Django 5.0.6 on 2024-10-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_rename_product_testproduct_prroduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testproduct',
            old_name='prroduct',
            new_name='product',
        ),
    ]
