# Generated by Django 5.0.6 on 2024-07-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_name_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='seo',
        ),
    ]
