# Generated by Django 5.0.6 on 2024-07-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_category_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
