# Generated by Django 5.0.6 on 2024-07-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_rename_icon_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
    ]
