# Generated by Django 5.0.6 on 2024-09-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_categorypreviewproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryPreviewProduct',
        ),
    ]
