# Generated by Django 5.0.6 on 2024-08-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vipuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIPUser',
        ),
    ]
