# Generated by Django 5.0.6 on 2024-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='meta_title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
