# Generated by Django 5.0.6 on 2024-08-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_alter_seo_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_shippings_costs', to='others.state')),
            ],
        ),
    ]
