# Generated by Django 5.0.6 on 2024-08-03 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_stateshippingcost_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateshippingcost',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_costs', to='others.state'),
        ),
        migrations.AlterField(
            model_name='stateshippingcost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_costs', to=settings.AUTH_USER_MODEL),
        ),
    ]
