# Generated by Django 5.0.6 on 2024-08-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_alter_stateshippingcost_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateshippingcost',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
