# Generated by Django 5.0.6 on 2024-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_alter_stateshippingcost_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateshippingcost',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
