# Generated by Django 5.0.6 on 2024-08-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_stateshippingcost_cost_to_home_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateShippingCost',
        ),
    ]
