# Generated by Django 5.0.6 on 2024-10-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_delete_stateshippingcost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEO',
        ),
    ]
