# Generated by Django 5.0.6 on 2024-07-12 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('others', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('home_delevery', models.BooleanField(blank=True, null=True)),
                ('is_abandoned', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('did_not_answer_phone', 'DidNotAnswerPhone'), ('postponed', 'Postponed'), ('canceled', 'Canceled'), ('canceled_from_client', 'CanceledFromClient'), ('waiting_for_client_call', 'WaitingForClientCall'), ('client_out_of_service', 'ClientOutOfService'), ('at_delevery_company', 'AtDeleveryCompany'), ('completed', 'Completed')], max_length=50)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='others.city')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='others.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
