# Generated by Django 5.0.6 on 2024-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('client_not_contacted_yet', 'ClientNotContactedYet'), ('confirmed', 'Confirmed'), ('did_not_answer_phone', 'DidNotAnswerPhone'), ('postponed', 'Postponed'), ('canceled', 'Canceled'), ('canceled_from_client', 'CanceledFromClient'), ('waiting_for_client_call', 'WaitingForClientCall'), ('client_out_of_service', 'ClientOutOfService'), ('at_delevery_company', 'AtDeleveryCompany'), ('completed', 'Completed')], max_length=50),
        ),
    ]
