# Generated by Django 5.0.6 on 2024-08-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_home_delevery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
