# Generated by Django 5.0.6 on 2024-08-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_address_order_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.TextField(blank=True, max_length=45, null=True),
        ),
    ]
