# Generated by Django 5.0.6 on 2024-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_city_order_shipping_city_remove_order_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
