# Generated by Django 5.0.6 on 2024-08-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_address_alter_order_shipping_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
