# Generated by Django 5.0.6 on 2024-08-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='home_delevery',
            new_name='shipping_to_home',
        ),
    ]
