# Generated by Django 5.0.6 on 2024-08-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_home_delevery_order_shipping_to_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
    ]
