# Generated by Django 5.0.6 on 2024-08-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_shipping_city'),
        ('others', '0008_stateshippingcost_cost_to_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.city'),
        ),
    ]
