# Generated by Django 5.0.6 on 2024-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_shipping_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
