# Generated by Django 5.0.6 on 2024-08-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('client_not_contacted_yet', 'ClientNotContactedYet'), ('confirmed', 'Confirmed'), ('did_not_answer_phone', 'DidNotAnswerPhone'), ('postponed', 'Postponed'), ('canceled', 'Canceled'), ('canceled_from_client', 'CanceledFromClient'), ('waiting_for_client_call', 'WaitingForClientCall'), ('client_out_of_service', 'ClientOutOfService'), ('at_delevery_company', 'AtDeleveryCompany'), ('completed', 'Completed')], default='client_not_contacted_yet', max_length=50),
        ),
    ]
