# Generated by Django 5.0.6 on 2024-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='client was not contacted yet', max_length=255),
        ),
    ]
