# Generated by Django 5.0.6 on 2024-08-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_order_user_order_store'),
        ('store', '0010_alter_stateshippingcost_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.status'),
        ),
    ]
