# Generated by Django 5.0.6 on 2024-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
