# Generated by Django 5.0.6 on 2024-08-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_product_quantity'),
        ('store', '0017_remove_visitor_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.visitor'),
        ),
    ]
