# Generated by Django 5.0.6 on 2024-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
