# Generated by Django 5.0.6 on 2024-08-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_order_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip_address',
        ),
    ]
