# Generated by Django 5.0.6 on 2024-08-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_remove_order_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
    ]
