# Generated by Django 5.0.6 on 2024-08-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
