# Generated by Django 5.0.6 on 2024-08-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_combination_index',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
    ]
