# Generated by Django 5.0.6 on 2024-08-15 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_options_remove_order_product_and_more'),
        ('product', '0041_product_max_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.stateshippingcost'),
        ),
    ]
