# Generated by Django 5.0.6 on 2024-08-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_product_order_shipping_state'),
        ('others', '0009_delete_stateshippingcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.state'),
        ),
    ]
