# Generated by Django 5.0.6 on 2024-08-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_order_shipping_cost_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
