# Generated by Django 5.0.6 on 2024-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_remove_order_shipping_cost_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='make_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
