# Generated by Django 5.0.6 on 2024-08-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_order_make_by_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='make_by_seller',
            new_name='made_by_seller',
        ),
    ]
