# Generated by Django 5.0.6 on 2024-08-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_rename_make_by_seller_order_made_by_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='show_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
