# Generated by Django 5.0.6 on 2024-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_order_show_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
