# Generated by Django 5.0.6 on 2024-10-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_order_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
